import './globals.css'


import { Inter } from 'next/font/google'
import { Header } from '../components/Header/Header'
import Home from './page'
import { Formlista } from '@/components/FormLIsta/Formlista'
// import { Base } from './Listagem/Base'
// import { Lista } from '@/components/ListaSugestao/Lista'
// import { Form } from '@/components/Form/Form'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="container-layout">
        <div>

          <Header />
        </div>
        <div className='teste'>
          <Home/>
        </div>

      </body>
    </html>
  )
}
